spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .html
        servlet:
            path: /
        static-path-pattern: /resources/**
    thymeleaf:
        check-template: true 
        check-template-location: true
        enabled: true
        prefix: /WEB-INF/views/
        suffix: .html
    resources:
        static-locations: classpath:/WEB-INF/resources/
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost/university
        username: tester
        password: test
        maxTotal: 20
        maxIdle: 10
        maxWaitMillis: -1
    jpa:
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        

        