spring:
    datasource:
        initialization-mode: always
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost/university
        username: tester
        password: test
        maxTotal: 20
        maxIdle: 10
        maxWaitMillis: -1
    jpa:
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    flyway:
        location: classpath:/db/migration
    mail:
        host: smtp.yandex.com
        username: 
        password: 
        port: 465
        protocol: smtps                        
mail:
    debug: true
