CREATE DATABASE university;
CREATE USER tester WITH PASSWORD 'test';
/c university;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "tester";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "tester";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "tester";
